Implement Map Events
GentenStudios/Phoenix pull request #281
Opened 2020-08-19 12:35 UTC by beeperdeeper089

Resolves: #
Authors:
@beeperdeeper089 

## Summary of changes
- Implements a map subscriber system.
- Fixes the issue with chunk updates when block break/places occur.
  
## Caveats
Does this introduce any new bugs?
- May result in some overhead, however blocking queue's may help fix that issue - we may need to improve cache efficiency with this later (my frame time graph showed essentially no changes so I think we're fine right now).

## On approval
Merge.

2020-09-16 23:38 UTC, apachano requested changes
Minor stuff, otherwise this all looks good

2020-09-16 23:38 UTC, apachano commented on Phoenix/Client/Include/Client/Graphics/ChunkMesher.hpp
> +#include <Common/Voxels/Chunk.hpp>
Chunk.hpp includes Block.hpp - we can remove block here

2020-09-16 23:38 UTC, apachano commented on Phoenix/Client/Include/Client/Voxels/BlockRegistry.hpp
>  				    }
Why flip these? Since most blocks are Solid wouldn't it be more performant to check that first? If not - you missed updating a comment

2020-09-18 13:28 UTC, beeperdeeper089 commented on Phoenix/Client/Include/Client/Voxels/BlockRegistry.hpp
>  				    }
Ah yes, I forgot to update the comment, but essentially the intention was to default to Solid in the case that the input is invalid or one is not selected but what might be a smarter idea is:
```cpp
block.category = voxels::BlockCategory::SOLID
if (category == "Solid") ...
if (category == "Liquid") ...
if (category == "Air") ...
```

2020-09-18 13:32 UTC, beeperdeeper089 commented on Phoenix/Client/Include/Client/Graphics/ChunkMesher.hpp
> +#include <Common/Voxels/Chunk.hpp>
The only reason I kept ``Block.hpp`` is because we are referencing ``voxels::BlockType`` directly, we don't need to but I feel that since we're using that exclusively too, it's worth including.

My opinion is that if we are exclusively using a specific class we should include it regardless - this may be a discussion worth having for coding standards as a whole.

2020-09-18 13:32 UTC, beeperdeeper089 commented on Phoenix/Client/Include/Client/Graphics/ChunkMesher.hpp
> +#include <Common/Voxels/Chunk.hpp>
Though, in this case we can move this include directly to the ``.cpp`` file since the header doesn't need it.

2020-09-18 15:42 UTC, apachano commented on Phoenix/Client/Include/Client/Graphics/ChunkMesher.hpp
> +#include <Common/Voxels/Chunk.hpp>
Definitely move it to the .cpp header - how do modern compilers handle redundant includes? My understanding of C is if you include it twice it actually builds the file twice which we don't want to happen.

2020-09-18 15:45 UTC, apachano commented on Phoenix/Client/Include/Client/Voxels/BlockRegistry.hpp
>  				    }
That makes sense - although now that I think about it by defaulting to Solid that means you don't have to define it in the Lua which reduces size and complexity there. In which case - if you dont define in Lua then it does all three checks in the CMS and we might as well go with what you did + remove the comment for the most optimized operation.

2020-09-18 15:48 UTC, beeperdeeper089 commented on Phoenix/Client/Include/Client/Graphics/ChunkMesher.hpp
> +#include <Common/Voxels/Chunk.hpp>
That's where the include guards/``#pragma once`` come in, they just make sure code isn't included twice since it might not only build twice but it'll end up failing since you've got multiple redefinitions, etc...

2020-09-18 16:17 UTC, beeperdeeper089 commented
sol2 strikes once again 😎

2020-09-19 04:54 UTC, apachano approved these changes

2020-09-19 04:54 UTC, merged