Link <filesystem> correctly on GCC 8.x
GentenStudios/Phoenix pull request #284
Opened 2020-08-20 17:09 UTC by JosiahWI

Resolves: Error linking <filesystem> on GCC 8.x
Authors:
@JosiahWI 

## Summary of changes
- CMake links std++fs library if GCC version < 9.x
  
## Caveats
Does this introduce any new bugs?

## On approval
Merge

2020-08-26 13:57 UTC, beeperdeeper089 requested changes

2020-08-26 13:57 UTC, beeperdeeper089 commented on Phoenix/ThirdParty/CMakeLists.txt
> +target_compile_definitions(EnTT INTERFACE $<$<PLATFORM_ID:Windows>:NOMINMAX>)
We will probably actually need ``NOMINMAX`` across the whole project, since we want to use std::min and std::max in a few places.

2020-08-26 14:00 UTC, beeperdeeper089 requested changes

2020-08-26 14:00 UTC, beeperdeeper089 commented on Phoenix/Common/CMakeLists.txt
> +                      PRIVATE $<$<AND:$<CXX_COMPILER_ID:GNU>,$<VERSION_LESS:$<CXX_COMPILER_VERSION>,9.0>>:stdc++fs>)
We're gonna need filesystem on all targets eventually, one of my PRs is using it in the client right now, and the server will end up needing it sooner or later, so I would recommend we put this in the ThirdParty CMake.

Another problem that this does not address is MacOS, where anything before 10.15 does NOT support filesystem regardless of what we tried (iirc), so we would need to test for that and make sure that works, or limit OS compatibility dependent on the version (if CMake can read that) - or figure out something for the package of clang that Mac's use. (I'm not a mac expert, nor do i own a mac so take this with a pinch of salt, @apachano would be the person to consult.)

2020-08-26 14:07 UTC, JosiahWI commented on Phoenix/ThirdParty/CMakeLists.txt
> +target_compile_definitions(EnTT INTERFACE $<$<PLATFORM_ID:Windows>:NOMINMAX>)
I think this is a better case for using add_definitions(), but not a great one. I'm trying to focus my suggested changes around the modern CMake design, which focuses heavily on using targets so that things are encapsulated. The equivalent C/++ code for add_definitions() would be a `#define NOMINMAX` in every single source file, including those in third party libraries.

2020-08-26 14:11 UTC, JosiahWI commented on Phoenix/Common/CMakeLists.txt
> +                      PRIVATE $<$<AND:$<CXX_COMPILER_ID:GNU>,$<VERSION_LESS:$<CXX_COMPILER_VERSION>,9.0>>:stdc++fs>)
CMake can test whether it works (try_compile()). I think it can test the OS version too, but it's been a bit since I looked at the documentation for those variables.

2020-08-26 14:19 UTC, JosiahWI commented on Phoenix/Common/CMakeLists.txt
> +                      PRIVATE $<$<AND:$<CXX_COMPILER_ID:GNU>,$<VERSION_LESS:$<CXX_COMPILER_VERSION>,9.0>>:stdc++fs>)
If we did use a global command for this, why would it go in ThirdParty? ThirdParty doesn't use <filesystem> and someone trying to maintain the build system won't have a clue where to find it or why it's there.

2020-09-08 11:11 UTC, beeperdeeper089 commented on Phoenix/Common/CMakeLists.txt
> +                      PRIVATE $<$<AND:$<CXX_COMPILER_ID:GNU>,$<VERSION_LESS:$<CXX_COMPILER_VERSION>,9.0>>:stdc++fs>)
That's why you would comment code, my opinion on it being in ThirdParty is because otherwise you have to attach to each and every target - and this is not a pretty solution, it's ugly (not your fault, it's just one of the downfalls of CMake). I feel leaving it in the main CMakeLists.txt woud just clutter it and it would just be harder to maintain with it being in multiple places all over the project (we might have to update something or the other one day and we would have to do that 3 times).

2020-09-08 11:13 UTC, beeperdeeper089 commented on Phoenix/Common/CMakeLists.txt
> +                      PRIVATE $<$<AND:$<CXX_COMPILER_ID:GNU>,$<VERSION_LESS:$<CXX_COMPILER_VERSION>,9.0>>:stdc++fs>)
I'm willing to get this merged as is though, since my concern isn't blocking it's just something we deal with or don't, I would just recommend adding this part into the Client/Server CMakes too since they'll *definitely* need filesystem within the next couple PRs of work (saves us having to do it).

2020-09-08 17:19 UTC, JosiahWI commented on Phoenix/Common/CMakeLists.txt
> +                      PRIVATE $<$<AND:$<CXX_COMPILER_ID:GNU>,$<VERSION_LESS:$<CXX_COMPILER_VERSION>,9.0>>:stdc++fs>)
I was going to wait to merge it in case I added more stuff, but I don't expect to do that in the near future now. I will look at this sometime this week, probably Saturday or Sunday, and add the flag to client and server. I also want to go back to your point about <filesystem> and MacOS. I will consider adding a check for that, although I can see why that's starting to get kinda messy if it's duplicated in three places. I could just put a compiler/OS check in the top level CMake and throw a fatal error with a more descriptive message than the linker error that would otherwise get thrown (not all gamers can read linker errors :-D).

2020-09-11 12:45 UTC, beeperdeeper089 commented on Phoenix/Common/CMakeLists.txt
> +                      PRIVATE $<$<AND:$<CXX_COMPILER_ID:GNU>,$<VERSION_LESS:$<CXX_COMPILER_VERSION>,9.0>>:stdc++fs>)
That sounds good. If you get around to it, hmu with a ping on discord since I haven't been super active on github for the last week and a bit or so (school started so been a bit busy :( )

2020-09-15 09:42 UTC, beeperdeeper089 approved these changes

2020-09-15 09:43 UTC, beeperdeeper089 commented
I've approved this but I want to test this once on my own computer to make sure it works (CI doesn't pass in the first place so I would hope this works as intended).

2020-09-15 13:12 UTC, JosiahWI commented
Could we merge in the fixes to the sol2 submodule first, so the CI passes?

2020-09-15 15:39 UTC, beeperdeeper089 commented
Well, we probably need CI on that PR to pass first.

2020-10-06 08:42 UTC, beeperdeeper089 commented
@JosiahWI If you get develop re-merged into this, I can re-approve and get this merged since we have sol2 passing and we've switched to GH Actions for CI now.

2020-10-06 14:39 UTC, JosiahWI commented
Sounds great, I'll get it done today.

2020-10-08 03:47 UTC, JosiahWI commented
I was busy and didn't get this done yet, I apologise for my slothfulness on this PR and I won't let it happen again.

2020-10-08 06:08 UTC, beeperdeeper089 commented
Don't worry about it, sometimes it happens. We're not really super concerned if it takes a few days for something to be done.

2020-10-09 02:45 UTC, JosiahWI commented
I made a simple mistake: I set the standard to C++11 and it should be C++17. I'll let you know when this is fixed.

2020-10-09 13:38 UTC, beeperdeeper089 requested changes

2020-10-09 13:38 UTC, beeperdeeper089 commented on Phoenix/Client/CMakeLists.txt
> +target_compile_features(${PROJECT_NAME} PRIVATE cxx_std_11)
I'm pretty sure it's better for portability to use set_target_properties with CXX_STANDARD rather than that. Even if they're equivalent, just use set_target_properties, there's no particular reason to change what we have there.

2020-10-09 13:38 UTC, beeperdeeper089 commented on Phoenix/Common/CMakeLists.txt
> +target_compile_features(${PROJECT_NAME} PUBLIC cxx_std_11)
Same as above.

2020-10-09 13:38 UTC, beeperdeeper089 commented on Phoenix/ThirdParty/CMakeLists.txt
> +target_compile_definitions(SDL2main INTERFACE SDL_MAIN_HANDLED)
Maybe put this definition with the Entt one underneath, so they're in one place rather than in the middle of everything, resulting in some spaghetti.

2020-10-09 13:39 UTC, beeperdeeper089 commented
Fix the cxx standard and these issues and we should be set to merge.

2020-10-09 16:51 UTC, beeperdeeper089 approved these changes

2020-10-09 16:51 UTC, beeperdeeper089 commented on Phoenix/Client/CMakeLists.txt
> +	CXX_STANDARD_REQUIRED ON
Thanks for correcting that! Didn't even notice 😂

2020-10-09 16:57 UTC, closed without merging