Feat escape menu settings
GentenStudios/Phoenix pull request #298
Opened 2020-10-25 17:43 UTC by apachano

Authors:
@apachano 

## Summary of changes
- Extends settings menu to allow editing of all settings that get registered

## On approval
Merge

2020-10-26 18:58 UTC, beeperdeeper089 requested changes
I'm yet to test this myself but you deffo need to run a quick clang-format on this

2020-10-26 18:58 UTC, beeperdeeper089 commented on Phoenix/Common/Include/Common/Settings.hpp
> +		int getMin() const {return m_minValue;};
Spacing, and you don't need the extra semicolon on the end.

2020-10-26 18:58 UTC, beeperdeeper089 commented on Phoenix/Common/Include/Common/Settings.hpp
> +		std::string getName() const;
Can we not return ``const std::string&``?

2020-10-26 19:03 UTC, apachano commented on Phoenix/Common/Include/Common/Settings.hpp
> +		std::string getName() const;
That would probably make sense

2020-10-26 19:06 UTC, apachano commented
Fixed the consts and ran autoformat @beeperdeeper089

2020-10-27 19:58 UTC, beeperdeeper089 approved these changes

2020-10-27 19:58 UTC, beeperdeeper089 commented
lgtm, merge if you're done otherwise i'll re-review if u update

2020-10-29 14:22 UTC, merged