Move save filepath generation to method.
GentenStudios/Phoenix pull request #299
Opened 2020-10-25 21:08 UTC by JosiahWI

Resolves: #
Authors:
@JosiahWI 

## Summary of changes
- A new method was added to get the path to a chunk's save file.
  
## Caveats
Does this introduce any new bugs?

## On approval
Wait for me for confirmation.

2020-10-27 23:19 UTC, tobyplowy commented
@JosiahWI Tell me when you want me to test build.

2020-10-28 01:46 UTC, JosiahWI commented
Ok, I'll let you know. I have two more parts to move into new functions.

2020-10-30 18:21 UTC, tobyplowy commented
Builds and seems to save as intended. Good job =D

2020-10-30 19:31 UTC, beeperdeeper089 requested changes
Code seems ok, I'm yet to test but I'll do that when I have more time.

Style wise, you've used braces to initialize in a lot of places where it's much more readable to just use an equals sign. A few places like the chunk constructor, using 2 values is fine.

2020-10-30 19:31 UTC, beeperdeeper089 commented on Phoenix/Common/Include/Common/Voxels/Map.hpp
> +	using chunkData_t = std::pair<phx::math::vec3, std::vector<std::byte>>;
You could get away with calling this ``ChunkData`` - this meets what we're using right now throughout the code. To make it more "safe", I would put this within the Map class since this is functionality the Map is offering throughout the codebase.

2020-10-30 19:31 UTC, beeperdeeper089 commented on Phoenix/Common/Include/Common/Voxels/Map.hpp
> +		inline constexpr const char* saveDir {"Saves/"};
Is there a particular reason for putting this in an anonymous namespace in the header? Could this not go in the source file and declutter it?

2020-10-30 19:31 UTC, beeperdeeper089 commented on Phoenix/Common/Include/Common/Voxels/Map.hpp
> +		bool parseChunkSave(std::string_view searchView, Chunk &chunk);
``Chunk& `` not ``Chunk &``

2020-10-30 19:31 UTC, beeperdeeper089 commented on Phoenix/Common/Include/Common/Voxels/Map.hpp
> +		bool loadChunk(const phx::math::vec3 chunkPos);
No point using const here unless you're going to do a const ref - which I'm assuming we should do.
Also, you don't need to use the whole namespace, you can just use ``math::vec3`` - however this is minor and tbh should probably be phx::math::vec3, but we'll need to change that everywhere else.

2020-10-30 19:31 UTC, beeperdeeper089 commented on Phoenix/Common/Include/Common/Voxels/Map.hpp
> +		void generateChunk(const phx::math::vec3 chunkPos);
Same as above about const ref.

2020-10-30 19:31 UTC, beeperdeeper089 commented on Phoenix/Common/Include/Common/Voxels/Map.hpp
> +		std::filesystem::path toSavePath(const phx::math::vec3i chunkPos) const;
const ref.

2020-10-30 19:31 UTC, beeperdeeper089 commented on Phoenix/Common/Source/Voxels/Map.cpp
> +	std::ofstream saveFile {toSavePath(static_cast<phx::math::vec3i>(pos))};
Readability wise, it's better do just do ``saveFile = ...`` rather than using ``{}`` initializers.

2020-10-30 19:31 UTC, beeperdeeper089 commented on Phoenix/Common/Source/Voxels/Map.cpp
> +	const std::size_t nChunksQueued {m_queue->size()};
Same as above but especially here, use ``const std::size_t chunksQueued = m_queue->size()``. Don't use the n, doesn't really describe anything.

2020-10-30 19:31 UTC, beeperdeeper089 commented on Phoenix/Common/Source/Voxels/Map.cpp
> +	for (std::size_t i {0}; i < nChunksQueued; ++i)
use = instead of {}, much more readable.

2020-10-30 19:31 UTC, beeperdeeper089 commented on Phoenix/Common/Source/Voxels/Map.cpp
> +		Chunk           chunk {data.first, m_referrer};
This is where initialization braces make sense, not like used above on POD.

2020-10-30 19:31 UTC, beeperdeeper089 commented on Phoenix/Common/Source/Voxels/Map.cpp
> +	Chunk::BlockList& blocks {chunk.getBlocks()};
Drop the braces, use an equals.

2020-10-30 19:31 UTC, beeperdeeper089 commented on Phoenix/Common/Source/Voxels/Map.cpp
> +	for (std::size_t delimiterPos {searchView.find_first_of(';')};
Again, braces.

2020-10-30 19:31 UTC, beeperdeeper089 commented on Phoenix/Common/Source/Voxels/Map.cpp
> +		const std::string blockName {searchView.substr(0, delimiterPos)};
Braces.

2020-10-30 19:31 UTC, beeperdeeper089 commented on Phoenix/Common/Source/Voxels/Map.cpp
> +	std::ifstream saveFile {
Braces.

2020-10-30 19:31 UTC, beeperdeeper089 commented on Phoenix/Common/Source/Voxels/Map.cpp
> +	for (std::size_t i {0}; i < Chunk::CHUNK_MAX_BLOCKS; ++i)
Braces.

2020-10-30 19:31 UTC, beeperdeeper089 commented on Phoenix/Common/Source/Voxels/Map.cpp
> +	const std::string posString {std::to_string(chunkPos.x) + '_' +
Braces.

2020-10-30 19:31 UTC, beeperdeeper089 commented on Phoenix/Common/Source/Voxels/Map.cpp
> +	const std::filesystem::path savePath {saveDir + m_save->getName() + '/' +
Braces.

2020-10-30 20:04 UTC, JosiahWI commented on Phoenix/Common/Include/Common/Voxels/Map.hpp
> +		inline constexpr const char* saveDir {"Saves/"};
That would work fine. I put it here because I think it belongs in another header and would be easier to move later.

2020-11-09 19:08 UTC, beeperdeeper089 approved these changes
LGTM, @tobyplowy can we get you to test this real quick?

2020-11-09 20:32 UTC, tobyplowy commented
Builds and seems to work as intended (Wasn't able to find any issues)

2020-11-09 20:33 UTC, merged

2020-11-09 20:33 UTC, tobyplowy commented
Thanks for the contribution.