Feat metadata
GentenStudios/Phoenix pull request #315
Opened 2020-11-29 20:18 UTC by apachano

Resolves: #121 
Authors:
@apachano 

## Summary of changes
- Implement a metadata storage system
- Integrate metadata storage system into blocks
- Record rotation on block placement in metadata on block
  
## Caveats
Does this introduce any new bugs?
- Rotation does not render
- Rotation is collected for every block, regardless of if its needed

## On approval
Merge

2020-11-29 21:32 UTC, beeperdeeper089 requested changes
Some basic changes, however a concern at the base level:

  - If we're supporting limited types, like ints, floats, vec3 (which I would assume would make sense - bare in mind I haven't put much thought into this past now) - does std::any really make sense or should we use something like std::variant which supports limited types and makes it easier for us to track/label types within it?

2020-11-29 21:32 UTC, beeperdeeper089 commented on Phoenix/Common/Include/Common/Metadata.hpp
> +/**
Do we want to bother standardising this? A few of our files have this but not that many.

2020-11-29 21:32 UTC, beeperdeeper089 commented on Phoenix/Common/Include/Common/Metadata.hpp
> +#include <any>
Put a newline here just for consistency between our includes and standard ones (since that's what we're doing in most of our other code).

2020-11-29 21:32 UTC, beeperdeeper089 commented on Phoenix/Common/Include/Common/Metadata.hpp
> +		 * @brief sets or inserts metadata
Being a bit pedantic (and I'm also a victim of this) but capitals and full stops.

2020-11-29 21:32 UTC, beeperdeeper089 commented on Phoenix/Common/Include/Common/Metadata.hpp
> +		/**
Newline between functions.

2020-11-29 21:32 UTC, beeperdeeper089 commented on Phoenix/Common/Include/Common/Metadata.hpp
> +		/**
Newline.

2020-11-29 21:32 UTC, beeperdeeper089 commented on Phoenix/Common/Include/Common/Metadata.hpp
> +		size_t size() { return m_data.size(); };
Use ``std::size_t``

2020-11-29 21:32 UTC, beeperdeeper089 commented on Phoenix/Common/Include/Common/Metadata.hpp
> +		void erase(const std::string& key) { m_data.erase(key); };
What happens if the key doesn't exist? (I think it just doesn't do anything, but would just like to double check)

2020-11-29 21:32 UTC, beeperdeeper089 commented on Phoenix/Common/Source/Metadata.cpp
> +			ser << std::string("int") << std::any_cast<int>(data.second);
1. Do you have to construct as ``std::string`` - if so that is yet another shortcoming of the serializer -_-. If that needs fixing I can shove in a patch for that.

2. I would argue against putting in the full data type, just putting ``i, f, s, v (int, float, string, vector)`` would be a better idea.

2020-11-29 21:32 UTC, beeperdeeper089 commented on Phoenix/Common/Source/Metadata.cpp
> +			LOG_FATAL("Metadata")
We don't want to be able to get to a stage where this should ever happen - if there is an invalid type we've really fucked up somewhere but it shouldn't have to affect the general end user - so maybe this should be a debug message and it's just ignored otherwise?

2020-11-29 21:32 UTC, beeperdeeper089 commented on Phoenix/Common/Include/Common/Voxels/Chunk.hpp
> +		void setBlockAt(math::vec3 position, Block newBlock);
``const math::vec3&``

2020-11-29 21:32 UTC, beeperdeeper089 commented on Phoenix/Common/Include/Common/Voxels/Chunk.hpp
> +		bool setMetadataAt(phx::math::vec3 position, const std::string& key,
Const ref.

2020-11-29 21:32 UTC, beeperdeeper089 commented on Phoenix/Common/Include/Common/Voxels/Map.hpp
> +		void       setBlockAt(math::vec3 pos, const Block& block);
Const ref on vec3.

2020-11-30 02:00 UTC, apachano commented on Phoenix/Common/Include/Common/Metadata.hpp
> +/**
I've been trying to, it does make the doxygen output nicer but its not super critical so I'm not concerned about pushing it if that makes sense?

2020-11-30 02:06 UTC, apachano commented on Phoenix/Common/Source/Metadata.cpp
> +			LOG_FATAL("Metadata")
I totally spaced it in implementation but I feel we should keep fatal but kill the program. Leaving this unhanded will lead to corruption.

2020-11-30 02:13 UTC, apachano commented on Phoenix/Common/Source/Metadata.cpp
> +			ser << std::string("int") << std::any_cast<int>(data.second);
You do have to construct as a string, if you don't then it will save as a cstring and in-turn will need retrieved as a cstring. Originally I put just a single character with the exception of a vec which may need expanded in the future to support additional types. 

We can convert this down to a single char - we just need to make a decision on how we would label a veci.

2020-11-30 02:48 UTC, apachano commented
@beeperdeeper089 I think I addressed everything, I also finished up everything I'm prepared to finish re rotation so there are a few changes I added making rotation optional.

2020-12-02 00:02 UTC, beeperdeeper089 commented on Phoenix/Common/Source/Metadata.cpp
> +			LOG_FATAL("Metadata")
Hmm, I'm not too sure, doing this leaves us in a spot of having many exit points through out the program (we definitely need to cut down on them), but I feel like metadata not being stored is not an issue enough that we should quit?

I'm not too sure, but my current argument is against exiting since I would assume it can't result in corruption or anything since it's just not outputting a piece of data.

2020-12-02 00:04 UTC, beeperdeeper089 reviewed
Replied to a comment.

2020-12-02 00:05 UTC, beeperdeeper089 commented on Phoenix/Common/Include/Common/Metadata.hpp
> +/**
Yeah sounds alright, I'll start telling Resharper to out that in my files too.

2020-12-02 00:42 UTC, apachano commented on Phoenix/Common/Source/Metadata.cpp
> +			LOG_FATAL("Metadata")
Well its not just not outputting data, its not serializing a value that we will attempt to read later. If it doesn't segfault on read we will get a chunk full of OOB/ random blocks instead of what we would want. At the very least we should abort the save to avoid corruption but since this will never happen -> going any further than throwing an exception is a bit overkill.

2020-12-06 16:27 UTC, apachano commented on Phoenix/Common/Source/Metadata.cpp
> +			ser << std::string("int") << std::any_cast<int>(data.second);
I converted to a single char, we can figure out handling multiple vec types later

2020-12-12 15:54 UTC, beeperdeeper089 requested changes
You still have a few comments left to address and a few new ones.

2020-12-12 15:54 UTC, beeperdeeper089 commented on Phoenix/Client/Include/Client/Voxels/BlockRegistry.hpp
> +				    if (rotH)
I'm assuming you meant ``if (rotV)``

2020-12-12 15:54 UTC, beeperdeeper089 commented on Phoenix/Client/Include/Client/Voxels/BlockRegistry.hpp
> +					    block.rotH = *rotV;
I'm assuming ``block.rotV``

2020-12-13 17:04 UTC, apachano commented
@beeperdeeper089 I think this is ready

2020-12-13 17:47 UTC, tobyplowy commented
Builds and runs. Can't find any issues.

2020-12-19 19:28 UTC, beeperdeeper089 commented
Looks good, just still the use of ``std::size_t`` in Metadata.hpp:69.

I'll approve and merge once that's in.

2020-12-19 23:56 UTC, apachano commented
@beeperdeeper089 Fixed the size_t

2020-12-20 09:09 UTC, beeperdeeper089 approved these changes

2020-12-20 09:10 UTC, merged