Feat hud
GentenStudios/Phoenix pull request #317
Opened 2020-11-30 18:25 UTC by apachano

Authors:
@apachano 

## Summary of changes
- Implements a super simple HUD that displays the block in the players hand and the block the player is looking at

## Caveats
Does this introduce any new bugs?
- No

## On approval
Merge

2020-11-30 19:11 UTC, beeperdeeper089 requested changes

2020-11-30 19:11 UTC, beeperdeeper089 commented on Phoenix/Client/Include/Client/Game.hpp
> +#include "HUD.hpp"
Use Client/Include/...

2020-11-30 19:40 UTC, apachano commented on Phoenix/Client/Include/Client/Game.hpp
> +#include "HUD.hpp"
Fixed . . . I must've let the IDE dot hat one :/

2020-12-01 18:05 UTC, beeperdeeper089 reviewed
Everything looks fine, I've just got two questions :)

2020-12-01 18:05 UTC, beeperdeeper089 commented on Phoenix/Client/Source/HUD.cpp
> +		ImGui::Text("%s", map->getBlockAt(target)->displayName.c_str());
What happens in the case of an out-of-bounds or air block? Does it display that too? (Sorry, haven't had the chance to test this out yet.)

2020-12-01 18:05 UTC, beeperdeeper089 commented on Phoenix/Client/Source/HUD.cpp
> +	ImGui::Begin("HUD", nullptr, ImGuiWindowFlags_NoResize);
Like Toby said on Discord, do we want to add whatever the flag is for disabling movement of the window?

2020-12-01 18:07 UTC, beeperdeeper089 commented on Phoenix/Client/Source/HUD.cpp
> +	ImGui::Begin("HUD", nullptr, ImGuiWindowFlags_NoResize);
Also, do we want to set an explicit size for the ImGui window? Maybe it can be either a set size or relative to the window size (problem with it being relative is if someone decides to scale the window down it might completely mess it up)

2020-12-01 19:27 UTC, Gerold55 commented on Phoenix/Client/Source/HUD.cpp
> +	ImGui::Begin("HUD", nullptr, ImGuiWindowFlags_NoResize);
I think it should be disabled by default but there should be a way to be able to activate it for people making mods imo...

2020-12-01 23:51 UTC, apachano commented on Phoenix/Client/Source/HUD.cpp
> +		ImGui::Text("%s", map->getBlockAt(target)->displayName.c_str());
It should display an OOB (those are solids right?), it will display an air block if there is no solid within range of the player.

2020-12-01 23:56 UTC, beeperdeeper089 commented on Phoenix/Client/Source/HUD.cpp
> +		ImGui::Text("%s", map->getBlockAt(target)->displayName.c_str());
Do we want it to - as a user facing HUD, would it make sense to hide things like OOB and air?

2020-12-02 00:35 UTC, apachano commented on Phoenix/Client/Source/HUD.cpp
> +	ImGui::Begin("HUD", nullptr, ImGuiWindowFlags_NoResize);
We probably want to set an explicit size once we know how wide it needs to be, although there isn't anything in-particular wrong with it setting the size based on container contents.

I can hunt down the flag and add it, not critical IMO but probably something we do want along with removing the title and possibly making the background transparent. Lots of style stuff that will eventually need to be added.

As far as modding support we could build that in later, thats definitely going to be a deeper discussion figuring out how we want to disable movement in those scenarios (which will likely be done via lua and probably repositioning instead of free movement?)

2020-12-02 10:42 UTC, beeperdeeper089 commented on Phoenix/Client/Source/HUD.cpp
> +	ImGui::Begin("HUD", nullptr, ImGuiWindowFlags_NoResize);
Sounds good to me 👍

2020-12-05 01:23 UTC, apachano commented on Phoenix/Client/Source/HUD.cpp
> +		ImGui::Text("%s", map->getBlockAt(target)->displayName.c_str());
You can break them so they should be solids, this should probably be the implementation anyways as the end user will want to break OOBs.

Air on the other hand - probably not.

2020-12-05 23:13 UTC, beeperdeeper089 commented on Phoenix/Client/Source/HUD.cpp
> +		ImGui::Text("%s", map->getBlockAt(target)->displayName.c_str());
Why would the user want to break OOB's? An OOB should only ever return on an error that is that the block you're trying to get doesn't actually exist - so why should they be able to break it? That would end up breaking a lot of systems and design if we want that to be a thing. I would assume we don't want things like Out of Bounds being usable and just an error type. I might be understanding wrong but this is what I've come to understand of an OOB block.

2020-12-05 23:25 UTC, apachano commented on Phoenix/Client/Source/HUD.cpp
> +		ImGui::Text("%s", map->getBlockAt(target)->displayName.c_str());
I mean - if you can't break it what do you do with it? Is it just a piece of the chunk you can never use again? An OOB is just to highlight that there was a block there but now it doesn't exist (usually because a module was removed or a definition was changed). Alternatively I'd argue that we would display an OOB as a proxy to air so the end-user never sees it and we never save it.

2020-12-05 23:41 UTC, beeperdeeper089 commented on Phoenix/Client/Source/HUD.cpp
> +		ImGui::Text("%s", map->getBlockAt(target)->displayName.c_str());
Ah, in the case you're highlighting, if a block no longer exists, due to something like a mod being removed, it would've replaced by core.unknown. Out of Bounds should only be returned if you're requesting a block that is out of the bounds of the map or a specific chunk. (this block doesn't necessarily have to exist, however it is a preventative measure in the case that it occurs.)

2020-12-06 00:34 UTC, apachano commented on Phoenix/Client/Source/HUD.cpp
> +		ImGui::Text("%s", map->getBlockAt(target)->displayName.c_str());
OHHHHH got it lol, well in that case it can't highlight an OOB and we are all good. I just got the two mixed up.

2020-12-06 16:21 UTC, apachano commented
Okay @beeperdeeper089 I locked + centered the window and added logic to not display non-solid blocks.

2020-12-12 15:49 UTC, beeperdeeper089 requested changes

2020-12-12 15:49 UTC, beeperdeeper089 commented on Phoenix/Client/Source/HUD.cpp
> +	    {m_window->getSize().x / 2 - 250, m_window->getSize().y - 100},
these are magic numbers, just make like a ``static constexpr int HUD_WIDTH`` variable or something so it makes sense when we come back to it.

2020-12-12 15:49 UTC, beeperdeeper089 commented on Phoenix/Client/Source/HUD.cpp
> +	ImGui::SetNextWindowSize(ImVec2(500, 50), ImGuiCond_Once);
Same as above, but you might need to put HUD_WIDTH / 2 for above.

2020-12-12 15:49 UTC, beeperdeeper089 commented on Phoenix/Client/Source/HUD.cpp
> +		ImGui::Text("%s", target_display.c_str());
Can we not just do:
```
if (target_block->category == voxels::BlockCategory::SOLID)
{
    ImGui::Text(..., targetBlock->displayName)
}
```
This prevents you copying the string unnecessarily.

2020-12-12 15:49 UTC, beeperdeeper089 commented on Phoenix/Client/Source/HUD.cpp
> +		auto target_block = map->getBlockAt(target);
Style, ``targetBlock``

2020-12-12 15:49 UTC, beeperdeeper089 commented on Phoenix/Client/Source/HUD.cpp
> +		std::string target_display;
I've recommended a way for you to get rid of this below, but if you keep this, needs to be renamed to ``targetDisplay``

2020-12-12 16:39 UTC, apachano commented on Phoenix/Client/Source/HUD.cpp
> +	    {m_window->getSize().x / 2 - 250, m_window->getSize().y - 100},
It couldn't be static since its calculated but I can create an extra variable for it

2020-12-12 16:45 UTC, apachano commented on Phoenix/Client/Source/HUD.cpp
> +		ImGui::Text("%s", target_display.c_str());
@beeperdeeper089 Then the UI will re-adjust every time you are/aren't looking at something solid because instead of filling it with an empty text element we don't add anything and everything below it slides up.

2020-12-12 17:22 UTC, JosiahWI commented on Phoenix/Client/Source/HUD.cpp
> +	    {m_window->getSize().x / 2 - 250, m_window->getSize().y - 100},
Not the function call part of the express though unless it's a constexpr function.

2020-12-13 03:06 UTC, apachano commented on Phoenix/Client/Source/HUD.cpp
> +	ImGui::SetNextWindowSize(ImVec2(500, 50), ImGuiCond_Once);
Oh I see what you are saying looking at this tonight

2020-12-13 17:04 UTC, apachano commented
@beeperdeeper089 I think this is ready

2020-12-13 17:37 UTC, tobyplowy commented
@apachano Builds and runs. 
Possible issue. Not really a big issue as this is temp and not meant to be final but still pointing it out for the record...
Changing the window size changes the position of the hotbar. (Tested on windows)
![image](https://user-images.githubusercontent.com/16853304/102019121-d3dce500-3d71-11eb-9dc3-4a3287185a9b.png)
![image](https://user-images.githubusercontent.com/16853304/102019189-4d74d300-3d72-11eb-843b-f80c0373a1e7.png)

2020-12-14 23:41 UTC, beeperdeeper089 reviewed
One comment, but otherwise this is ready to merge.

2020-12-14 23:41 UTC, beeperdeeper089 commented on Phoenix/Client/Source/HUD.cpp
> +	    ImGuiCond_Once);
Removing ImGuiCond_Once would fix Toby's issue. Also, will using it here prevent any future SetNextWindowPos calls? From what I read of the documentation it would, but it doesn't highlight whether it actually does or not so we should probably check or just remove it since I would assume the performance difference is negligible (we're not using ImGui particularly extensively in the first place).

2020-12-15 11:59 UTC, beeperdeeper089 commented on Phoenix/Client/Source/HUD.cpp
> +	    {m_window->getSize().x / 2 - 250, m_window->getSize().y - 100},
^ Just like ``static constexpr int HUD_WIDTH = 500``

2020-12-20 00:05 UTC, apachano commented on Phoenix/Client/Source/HUD.cpp
> +	    ImGuiCond_Once);
It doesn't prevent any, just that particular call won't call again. I forgot why I added it though.

2020-12-20 09:08 UTC, beeperdeeper089 approved these changes
Lgtm

2020-12-20 09:09 UTC, merged