WIP - Feat inventories
GentenStudios/Phoenix pull request #323
Opened 2021-01-04 23:19 UTC by apachano

Resolves: #34 
Authors:
@apachano 

## Summary of changes
- Implements creative and player inventories

## Caveats
Does this introduce any new bugs?
- "held" item shows up in statically placed inv slot instead of replacing cursor

## QA Notes
- Items in creative inventory should be unlimited
- Items in player inventory should be limited
- Only one item should be held at a time
- Only one item should fix in a slot
- First 10 slots in inventory should map to hot bar

## On approval
Wait for me

2021-01-04 23:39 UTC, tobyplowy commented
@apachano CI build fails.

2021-01-05 01:44 UTC, apachano commented
Fixed the build issue

2021-01-05 23:10 UTC, tobyplowy commented
Build failed with 1 Error.
[build log).txt](https://github.com/GentenStudios/Phoenix/files/5773063/message.1.txt)

2021-01-07 03:04 UTC, apachano commented
@tobyplowy Should be fixed now

2021-01-07 16:17 UTC, tobyplowy commented
Builds and runs.
Also this is so COOL.
![image](https://user-images.githubusercontent.com/16853304/103916008-36749700-510c-11eb-9f55-7896c390e429.png)
Good stuff so far keep it up!

2021-01-15 14:08 UTC, beeperdeeper089 requested changes

2021-01-15 14:08 UTC, beeperdeeper089 commented on Phoenix/Client/Source/HUD.cpp
> +		for (size_t i = 0; i < hand.size; i++)
std::size_t

2021-01-15 14:08 UTC, beeperdeeper089 commented on Phoenix/Client/Source/InventoryUI.cpp
> +				LOG_DEBUG("Inv") << "Click";
Do we still need this debug statement?

2021-01-15 14:08 UTC, beeperdeeper089 commented on Phoenix/Common/Include/Common/Voxels/Inventory.hpp
> +		size_t                 m_size;
std::size_t

2021-01-15 14:08 UTC, beeperdeeper089 commented on Phoenix/Common/Include/Common/Voxels/Inventory.hpp
> +		size_t                        getSize() const { return m_size; };
std::size_t

2021-01-16 20:59 UTC, apachano commented on Phoenix/Client/Include/Client/HUD.hpp
> +		static constexpr float WIDTH  = 588;
Added compile time calculation

2021-01-16 21:00 UTC, apachano commented on Phoenix/Client/Source/Game.cpp
> +	m_registry->emplace<Hand>(m_player, std::size_t(1), m_playerInventory);
Apparently I can, I remember hitting a compile error but its gone now

2021-01-17 18:23 UTC, beeperdeeper089 approved these changes
Lgtm, wait for Toby to test and I'm happy to merge.

2021-01-17 18:57 UTC, tobyplowy commented
Bulds and runs as intened. Hotbar issue fixed. 
Dud stuff austin my guy.

2021-01-17 19:20 UTC, merged