WIP - Initial implementation and example of tests
GentenStudios/Phoenix pull request #332
Opened 2021-01-17 21:51 UTC by apachano

Authors:
@apachano 

## Summary of changes
- Add testing framework
- Add tests to inventory system
  
## Caveats
Does this introduce any new bugs?
- No

## On approval
Wait for me (need to figure out GH actions)

2021-01-18 15:51 UTC, beeperdeeper089 requested changes

2021-01-18 15:51 UTC, beeperdeeper089 commented on Phoenix/Common/CMakeLists.txt
> +option(BUILD_TESTS OFF)
Do we want to rename this to PHX_BUILD_TESTS?

2021-01-18 15:51 UTC, beeperdeeper089 commented on Phoenix/Common/CMakeLists.txt
> +add_executable(${PROJECT_NAME}_test ${Headers} ${Sources} ${Tests})
Can we move this stuff into another CMake file in the Tests directory?

2021-01-18 15:51 UTC, beeperdeeper089 commented on Phoenix/Common/Test/Math/Vector3.test.cpp
> +	REQUIRE(Vector3<int> {1, 1, 1} + Vector3<int> {1, 1, 1} ==
We need more test cases - probably randomised as well.

We need basic multiplication, division, addition and subtraction. I could probably fill that in for you at some point if you can't be bothered for this PR.

2021-01-18 15:51 UTC, beeperdeeper089 commented on Phoenix/ThirdParty/CMakeLists.txt
> +		#Catch2::Catch2
If it's just commented probably just remove it.

2021-01-18 15:51 UTC, beeperdeeper089 commented on Phoenix/Common/CMakeLists.txt
> +		PRIVATE
Your editor has replaced tab with 8 spaces so we probably want to fix that.

2021-01-18 15:51 UTC, beeperdeeper089 commented on Phoenix/Common/CMakeLists.txt
> +#if(BUILD_TESTS)
Remove if not needed.

However I'm assuming it's meant to disable/enable tests so it'd be nice if we can make that functional.

2021-01-18 16:12 UTC, apachano commented on Phoenix/Common/CMakeLists.txt
> +add_executable(${PROJECT_NAME}_test ${Headers} ${Sources} ${Tests})
Not sure how with CMake - I can dig but initially trying to move it IDK how to get the headers and sources variable down to that file.

2021-01-18 16:13 UTC, apachano commented on Phoenix/Common/CMakeLists.txt
> +option(BUILD_TESTS OFF)
Actually, I never ended up using this.

2021-01-18 16:24 UTC, apachano commented on Phoenix/Common/CMakeLists.txt
> +option(BUILD_TESTS OFF)
I'mma implement it b/c that would make sense lol

2021-01-18 16:25 UTC, apachano commented on Phoenix/Common/Test/Math/Vector3.test.cpp
> +	REQUIRE(Vector3<int> {1, 1, 1} + Vector3<int> {1, 1, 1} ==
Agreed - but this was just a demo of "here is how you do shit"/ "this works". We will need to add some tickets to implement tests for existing code.

2021-01-18 16:32 UTC, apachano commented
@beeperdeeper089 Fixed everything but moving the test code to the sub directory, it was throwing a fit when I tried.

2021-01-19 16:33 UTC, beeperdeeper089 commented on Phoenix/Common/CMakeLists.txt
> +add_executable(${PROJECT_NAME}_test ${Headers} ${Sources} ${Tests})
It propogates, you can just do ${Headers} will work

2021-01-19 16:33 UTC, beeperdeeper089 commented on Phoenix/Common/Test/Math/Vector3.test.cpp
> +	REQUIRE(Vector3<int> {1, 1, 1} + Vector3<int> {1, 1, 1} ==
Sounds good!

2021-01-19 16:36 UTC, beeperdeeper089 commented
I'll merge this for now, we can make a card for moving it in later. I might try get that done today if I can be bothered.

2021-01-19 16:36 UTC, beeperdeeper089 approved these changes

2021-01-19 16:36 UTC, merged