Feat audio
GentenStudios/Phoenix pull request #345
Opened 2021-01-28 19:44 UTC by apachano

Resolves: #327 
Authors:
@apachano 

## Summary of changes
- Implement Soloud library
- Implement Background music
- Implement API for registering sounds
- Implement API for triggering sounds on block place event
- Implement API for triggering sounds on block break event
  
## Caveats
Does this introduce any new bugs?
- Until an OSX bug is merged into Soloud's master branch, we are sourcing from a forked version of the repo

## On approval
Merge

2021-01-28 19:51 UTC, tobyplowy commented
Mac Ci fails. Always mac for whatever reason.

2021-01-28 20:54 UTC, apachano commented
@tobyplowy The submodule BS is fixed

2021-01-29 13:42 UTC, tobyplowy commented
PR fails to build for me. 
[message.txt](https://github.com/GentenStudios/Phoenix/files/5894125/message.txt)

2021-01-30 00:58 UTC, tobyplowy approved these changes

2021-02-05 13:53 UTC, beeperdeeper089 requested changes
Mainly documentation and we should be able to not need to use the SDL audio backend - since I think it's not very good anyways

2021-02-05 13:53 UTC, beeperdeeper089 commented on Phoenix/Client/Include/Client/Voxels/AudioEventHandler.hpp
> +namespace phx::client
Doc this.

2021-02-05 13:53 UTC, beeperdeeper089 commented on Phoenix/ThirdParty/CMakeLists.txt
> +set(WITH_SDL2 ON)
We don't have to use SDL?

[This](https://sol.gfxile.net/soloud/basics.html) shows that we can probably get away with it using default system backends - if you can get it compiling (I remember spending a while getting that working when I tried this library out for the first time).

2021-02-05 20:19 UTC, apachano commented on Phoenix/Client/Include/Client/Voxels/BlockRegistry.hpp
> +							    LOG_WARNING("MODDING")
This has been a complaint since day 1 for me, word wrap is a thing for most IDEs.

2021-02-05 20:29 UTC, apachano commented
@tobyplowy Can you re-QA to make sure the automatic audiobackend search works. Volume is a touch low on Linux but good enough for now.

2021-02-07 23:20 UTC, tobyplowy commented
How do I test the automatic audio back end search ? 

Also PR builds and runs.

2021-02-07 23:32 UTC, apachano commented
All tested lol, I switched the backend in the source so if it runs it's
good.

On Sun, Feb 7, 2021, 3:20 PM Toby plowy (Toby109tt) <
notifications@github.com> wrote:

> How do I test the automatic audio back end search ?
>
> Also PR builds and runs.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/GentenStudios/Phoenix/pull/345#issuecomment-774786983>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AARG5OLLCOJCMKJRXIYUZ4LS54N4XANCNFSM4WXT6UOA>
> .
>

2021-02-08 00:53 UTC, beeperdeeper089 commented
I'll run clang-tidy on this and approve once I've done it in the morning

2021-02-10 16:33 UTC, beeperdeeper089 approved these changes

2021-02-10 16:34 UTC, beeperdeeper089 commented
"morning" being completely metaphorical

2021-02-10 16:34 UTC, beeperdeeper089 commented
but, merge conflict so have fun

2021-02-10 17:32 UTC, beeperdeeper089 approved these changes

2021-02-10 17:32 UTC, merged