Implement Vec3 object in Lua and upgrade event callbacks
GentenStudios/Phoenix pull request #354
Opened 2021-02-11 19:13 UTC by apachano

Authors:
@apachano 

## Summary of changes
- Implement a vec3 class mapping to lua usertype
- Upgrade block and item events to use vec3 instead of three floats
  
## Caveats
- None

## On approval
Merge

2021-02-16 18:38 UTC, beeperdeeper089 requested changes
On phone so nothing major, I'll re-review once I'm on my computer w some time

2021-02-16 18:38 UTC, beeperdeeper089 commented on Phoenix/Client/Source/Game.cpp
> +		                               LOG_DEBUG("TEMP") << block->id;
Do you still need this?

2021-02-16 18:38 UTC, beeperdeeper089 commented on Phoenix/Common/Include/Common/CMS/ModManager.inl
> +	sol::usertype<T> ModManager::registerType(std::string name,
Const std::string&

2021-02-16 18:38 UTC, beeperdeeper089 commented on Phoenix/Common/Source/Voxels/Chunk.cpp
> +			LOG_DEBUG("CHUNK") << "onPlace" << newBlock.type->id;
Do we need this?

2021-02-16 20:47 UTC, apachano commented
I addressed those thoughts

2021-02-18 13:35 UTC, beeperdeeper089 approved these changes
LGTM.

2021-02-18 16:27 UTC, merged