Refactor Skybox and Selectionbox renderers into their own objects.
GentenStudios/Phoenix pull request #364
Opened 2021-05-18 21:46 UTC by apachano

Authors: @apachano 

## Summary of changes
- Refactors WorldRenderer.hpp into SkyboxRenderer.hpp with the intent that the object only handles the skybox.
- Splits SelectionboxRenderer.hpp from ChunkRenderer.hpp with the intent that the chunk renderer only renders chunks.
- Removes Camera from ChunkRenderer.hpp logic
  
## Caveats
- The chunk renderer needs further cleanup, its definitely still messy

## Testing notes
Nothing functionally should have changed, this is purely a code reorganization in preparation for adding an additional renderer.

## On approval
Merge

2021-05-18 23:40 UTC, tobyplowy commented
PR builds and runs.

2021-05-21 13:52 UTC, beeperdeeper089 requested changes

2021-05-21 13:52 UTC, beeperdeeper089 commented on Phoenix/Client/Include/Client/Graphics/SelectionboxRenderer.hpp
> +	class SelectionboxRenderer
``SelectionBoxRenderer`` for PascalCase consistency.

2021-05-21 13:52 UTC, beeperdeeper089 commented on Phoenix/Client/Include/Client/Graphics/SelectionboxRenderer.hpp
> +	private:
Newline for styling + my ocd

2021-05-26 17:18 UTC, beeperdeeper089 requested changes

2021-05-26 17:18 UTC, beeperdeeper089 commented on Phoenix/Common/Include/Common/Actor.hpp
> +		    math::vec3      position = {0,0,0},
Are we sure we want to allow default initialisation of the position and rotation?
I feel like that should always be explicitly set just due to the fact that 0, 0, 0 could spawn you inside the world randomly and could give us a bug we didn't forsee later.

2021-05-27 03:25 UTC, tobyplowy commented on Phoenix/Common/Include/Common/Actor.hpp
> +		    math::vec3      position = {0,0,0},
Yeah Vyom has a point here.

2021-05-27 19:56 UTC, apachano commented on Phoenix/Common/Include/Common/Actor.hpp
> +		    math::vec3      position = {0,0,0},
That makes sense, I'll remove the default initialisation

2021-05-28 19:55 UTC, beeperdeeper089 approved these changes
LGTM.

2021-05-29 00:44 UTC, merged