Consolidate duplicate code into single function
GentenStudios/Phoenix pull request #368
Opened 2021-06-18 02:31 UTC by apachano

Authors:
@apachano 

## Summary of changes
- Consolidate duplicate code into single function
  
## Caveats
Does this introduce any new bugs?
- A constructor making GL calls may be an issue

## On approval
Merge

2021-06-18 18:07 UTC, beeperdeeper089 requested changes

2021-06-18 18:07 UTC, beeperdeeper089 commented on Phoenix/Client/Include/Client/Graphics/ChunkRenderer.hpp
> +        gfx::ShaderPipeline m_renderPipeline{};
Do we actually need to default init this? The class does have a default constructor, and do we want to use ``= {}`` cos imo it does look tidier?

2021-06-18 18:07 UTC, beeperdeeper089 commented on Phoenix/Client/Include/Client/Graphics/ChunkRenderer.hpp
> +        struct ChunkRenderData
This is fine, but delete the copy constructor and copy and move assignment operators so we don't get weird resource lifetime bugs one day due to copies and deletes

2021-06-18 18:07 UTC, beeperdeeper089 commented on Phoenix/Client/Include/Client/Graphics/ChunkRenderer.hpp
> +            unsigned int vao{};
And do we want to use ``= {}`` cos imo it looks tider.

2021-06-18 18:08 UTC, beeperdeeper089 commented
Like you said, constructor making GL calls could get annoying, so just mark the coup constructor as delete as well as the move and copy assignment operators, you can leave the move constructor as default since that shouldn't interfere.

2021-06-18 18:08 UTC, apachano commented on Phoenix/Client/Include/Client/Graphics/ChunkRenderer.hpp
> +        gfx::ShaderPipeline m_renderPipeline{};
idk, clang-tidy was throwing a fit that it wasn't ever initialized so I rolled with it

2021-06-18 18:09 UTC, apachano commented
@beeperdeeper089 Alternatively it may make sense for this to be a private member function on the renderer itself? That was my original plan but for some reason I liked this last night

2021-06-18 18:11 UTC, beeperdeeper089 commented
I think it may make sense as a private member, in my opinion RAII for OpenGL is quite a non-intuitive way of working it bc it's just horrid for it 😂

2021-06-19 15:21 UTC, beeperdeeper089 requested changes

2021-06-19 15:21 UTC, beeperdeeper089 commented on Phoenix/Client/Include/Client/Graphics/ChunkRenderer.hpp
> +        static ChunkRenderData generate(std::vector<float> mesh);
``const ref`` or r-value ref to move, otherwise we're copying a potentially somewhat large amount of data

2021-06-22 09:47 UTC, beeperdeeper089 approved these changes

2021-06-22 09:47 UTC, merged